#!/bin/bash

cd /usr/local/share/crubadan/ga/sonrai

# two args; first is regex to replace (BRE!), second is replacement
fixone()
{
TMPCHOMHAD=`mktemp`
echo "Fixing \"$1\"..."
find . -name '*.dat' | xargs grep -l "^title: .*$1" > $TMPCHOMHAD
if [ -s $TMPCHOMHAD ]
then
	cat $TMPCHOMHAD | xargs sed -i "/^title: /s/$1/$2/"
	echo "Applied change to " `cat $TMPCHOMHAD | wc -l` " lines"
else
	echo "Change not applied; no examples found..."
fi
rm -f $TMPCHOMHAD
}


fixone 'NA GAEIL . THE GAELIC PEOPLE ' 'NA GAEIL '
exit 0
# sic - tobar.ie
fixone 'mhúinteoiri' 'mhúinteoirí'
# sic
fixone 'Colaiste na bhFiann' 'Coláiste na bhFiann'
fixone 'Better Government -' 'Rialtas Níos Fearr -'
fixone 'Better Regulation -' 'Rialáil Níos Fearr -'
fixone 'Welcome to the Railway Procurement Agency' 'An Ghníomhaireacht Um Fháil Iarnród'
# sic
fixone 'Sonrai an Ghrupa' 'Sonraí an Ghrúpa'
fixone 'Cork City Council > Our Services: Corporate Affairs' 'Comhairle Cathrach Chorcaí > Seirbhísí: Cúrsaí Gnó'
fixone 'Arts Council Ireland News, Information' 'An Chomhairle Ealaíon: Nuacht, Eolas'
# sic!
fixone 'Arts Council/An Chomhaile Ealaíon' 'An Chomhairle Ealaíon'
fixone 'Seanad Debates ' 'Díospóireachtaí Seanaid '
fixone 'Dáil Debates ' 'Díospóireachtaí Dála '
fixone 'Seanad Debate ' 'Díospóireacht Seanaid '
fixone 'Dáil Debate ' 'Díospóireacht Dála '
fixone 'Higher Education Authority . An tÚ' 'An tÚ'
# RISKY
#fixone 'Press Releases' 'Preaseisiúintí'
fixone ' - Information By Topic' ' Eolas De Réir Ábhair'
fixone 'National Roads Authority \?:' 'An tÚdarás um Bóithre Náisiúnta:'
fixone 'Article from An Ch' 'Alt ón Ch'
fixone '  Oral Answers' '  Freagraí ó bhéal'
fixone ' - Volume ' ' - Imleabhar '
fixone '\([^a-zA-Z]\) Annual Report' '\1 Tuarascáil Bhliantúil'
fixone 'Public Jobs -' 'Seirbhís Um Cheapacháin Phoiblí -'
fixone 'Royal Irish Academy' 'Acadamh Ríoga na hÉireann'
#  RISKY - tgrep manually first and fix ones like "Order Publications", etc.
#fixone 'Publications' 'Foilseacháin'
fixone 'State Examination Commission' 'Coimisiún na Scrúduithe Stáit'
find . -name '*.dat' | xargs grep -l "^title: Gan Teideal" | xargs egrep -l '^url: http://www\.nuacht\.com/story/' | xargs sed -i "s/^title: .*/title: Alt i Lá/"
fixone 'Department of the Taoiseach - Roinn an Taoisigh' 'Roinn an Taoisigh'
fixone 'Department of the Taoiseach - ' 'Roinn an Taoisigh - '
fixone 'Irish language residence' 'Aonad na Gaeilge'
fixone 'NUI Galway,' 'Ollscoil na hÉireann Gaillimh,'
fixone 'Galway County Library Text Only' 'Leabharlann Chontae na Gaillimhe'
fixone 'Galway County Library' 'Leabharlann Chontae na Gaillimhe'
fixone 'Selected instruments taken from the Treaties' 'Cnuasach na gConarthaí'
fixone 'Consolidated versions' 'Leaganacha comhdhlúite'
fixone 'Web Links' 'Naisc Ghréasáin'
fixone 'Foras na Gaeilge - Eolaire - Business' 'Foras na Gaeilge - Eolaire - Gnó'
fixone 'Heritage Ireland - ' 'Oidhreacht na hÉireann - '
fixone 'Department of Community, Rural and Gaeltacht Affairs' 'An Roinn Gnóthaí Pobail, Tuaithe agus Gaeltachta'
fixone 'Fáilte go Cló Iar-Chonnachta .CIC..  - Welcome to Cló Iar-Chonnachta .CIC.' 'Fáilte go Cló Iar-Chonnachta (CIC)'
fixone 'TG4 - Irish language television channel - Teilifis Gaeilge' 'TG4 - Teilifís Ghaeilge'
fixone 'Untitled Document$' 'Gan Teideal'
fixone 'Untitled$' 'Gan Teideal'
fixone 'Department of Education . Science -' 'An Roinn Oideachais Agus Eolaíochta -'
fixone '2003 Special Olympics' 'Cluichí Oilimpeacha Speisialta 2003'
fixone 'Ombudsman.s Annual Report' 'Tuarascáil Bhliantúil an Ombudsman'
fixone 'FÁS Annual Report . Financial Statements' 'FÁS: Tuarascáil Bhliantúil agus Ráitis Airgeadais'
fixone 'Ceisteanna--Questions' 'Ceisteanna'
fixone 'January,\? \([0-9][0-9][0-9][0-9]\)' 'Eanáir \1'
fixone 'February,\? \([0-9][0-9][0-9][0-9]\)' 'Feabhra \1'
fixone 'March,\? \([0-9][0-9][0-9][0-9]\)' 'Márta \1'
fixone 'April,\? \([0-9][0-9][0-9][0-9]\)' 'Aibreán \1'
fixone 'May,\? \([0-9][0-9][0-9][0-9]\)' 'Bealtaine \1'
fixone 'June,\? \([0-9][0-9][0-9][0-9]\)' 'Meitheamh \1'
fixone 'July,\? \([0-9][0-9][0-9][0-9]\)' 'Iúil \1'
fixone 'August,\? \([0-9][0-9][0-9][0-9]\)' 'Lúnasa \1'
fixone 'September,\? \([0-9][0-9][0-9][0-9]\)' 'Meán Fómhair \1'
fixone 'October,\? \([0-9][0-9][0-9][0-9]\)' 'Deireadh Fómhair \1'
fixone 'November,\? \([0-9][0-9][0-9][0-9]\)' 'Samhain \1'
fixone 'December,\? \([0-9][0-9][0-9][0-9]\)' 'Nollaig \1'
fixone 'AN PHOBLACHT.REPUBLICAN NEWS' 'AN PHOBLACHT'
fixone 'Health Service Executive  ' 'Feidhmeannacht na Seirbhíse Sláinte: '
fixone 'Foras na Gaeilge - Directory' 'Foras na Gaeilge - Eolaire'
fixone 'Event details$' 'Sonraí imeachta'
fixone 'Peoples Republic Of Cork Forums' 'Daonphoblacht Chorcaí'
fixone 'Yahoo! Groups ' 'Grúpaí Yahoo! '
fixone 'Microsoft Word - \([^ ]\)' '\1'
fixone 'Microsoft Download Center' 'Lárionad Íosluchtaithe'
fixone 'eolas-ibi Messages : Message \([0-9]*\) of ' 'Teachtaireachtaí eolas-ibi : Teachtaireacht \1 as '
fixone 'Arts Council Ireland News - Press Releases' 'An Chomhairle Ealaíon - Preasráitis'
fixone 'Office of the Ombudsman' 'Oifig an Ombudsman'
fixone 'Office of the Information Commissioner' 'Oifig an Choimisinéara Faisnéise'
fixone ' - Wikipedia$' ' - Vicipéid'
fixone 'SEANCHAS-L Archives ' 'Cartlann SEANCHAS-L '
fixone 'GAELIC-L Archives ' 'Cartlann GAELIC-L '
fixone 'GAEILGE-A Archives ' 'Cartlann GAEILGE-A '
fixone 'January \([0-9][0-9][0-9][0-9]\)' 'Eanáir \1'
fixone 'February \([0-9][0-9][0-9][0-9]\)' 'Feabhra \1'
fixone 'March \([0-9][0-9][0-9][0-9]\)' 'Márta \1'
fixone 'April \([0-9][0-9][0-9][0-9]\)' 'Aibreán \1'
fixone 'May \([0-9][0-9][0-9][0-9]\)' 'Bealtaine \1'
fixone 'June \([0-9][0-9][0-9][0-9]\)' 'Meitheamh \1'
fixone 'July \([0-9][0-9][0-9][0-9]\)' 'Iúil \1'
fixone 'August \([0-9][0-9][0-9][0-9]\)' 'Lúnasa \1'
fixone 'September \([0-9][0-9][0-9][0-9]\)' 'Meán Fómhair \1'
fixone 'October \([0-9][0-9][0-9][0-9]\)' 'Deireadh Fómhair \1'
fixone 'November \([0-9][0-9][0-9][0-9]\)' 'Samhain \1'
fixone 'December \([0-9][0-9][0-9][0-9]\)' 'Nollaig \1'
fixone 'Irish dictionary online, Irish gaelic.*' 'Foclóir Béarla-Gaeilge ar líne'
fixone 'BBC - Northern Ireland - Irish -' 'BBC - Tuaisceart Éireann - An Ghaeilge -'
fixone 'BBC - Northern Ireland - Irish Language -' 'BBC - Tuaisceart Éireann - An Ghaeilge -'
fixone 'BBC - Northern Ireland - Irish Music' 'BBC - Tuaisceart Éireann - Ceol Éireannach'
fixone ':: View topic ' ':: Topaic '
fixone 'The Daltaí Boards' 'Cláriomrá Daltaí na Gaeilge'
fixone 'The Pensions Board' 'An Bord Pinsean'
fixone 'The Dormant Accounts Fund Disbursements Board' 'An Bord Eisíocaíochtaí Chiste na gCuntas Díomhaoin'
fixone 'Government of Ireland - Department of Finance' 'Rialtas na hÉireann - An Roinn Airgeadais'
fixone 'Department of Foreign Affairs - Government of Ireland' 'An Roinn Gnóthaí Eachtracha - Rialtas na hÉireann'
fixone 'European Constitution - Preamble - Department of Foreign Affairs - Ireland' 'Bunreacht na hEorpa - Brollach - An Roinn Gnóthaí Eachtracha - Rialtas na hÉireann'

echo "Don't forget to rerun swish-e for TEIDIL index"
