#!/bin/bash
#  since togail works with percentages, this check is not redundant!
cd /usr/local/share/crubadan/ga
find ciu -name '*.txt' | xargs egrep -i -l '\b(gu|aig|ri|tha)\b' |
while read x
do
	GA=`togail ga mutual "$x" | sed 's/^0\.//; s/.$//; s/^0//'`
	GD=`togail gd mutual "$x" | sed 's/^0\.//; s/.$//; s/^0//'`
#	echo $x "ga" $GA "gd" $GD
	if [ $((${GD}+5)) -gt ${GA} ]
	then
		echo "$x"
	fi
done
