#!/bin/bash

preindex()
{
perl reamhinneacs ABAIRT     # (ciu->ABAIRT  using Gramadoir (get_sentences))
perl reamhinneacs NNN        # (ABAIRT->NNN  using tolower)
perl reamhinneacs YNN        # (ABAIRT->YNN  using tokenize+strip_mutations)
perl reamhinneacs YYN        # (ABAIRT->YYN  using Stemmer)
perl reamhinneacs ABAIRT-CH  # (ciu->ABAIRT-CH  using Caighdean)
perl reamhinneacs NNY        # (ABAIRT-CH->NNY  using tolower)
perl reamhinneacs YNY        # (ABAIRT-CH->YNY  using tokenize+strip_mutations)
perl reamhinneacs YYY        # (ABAIRT-CH->YYY  using Stemmer)
rm -f /usr/local/share/crubadan/ga/ANCIU
touch /usr/local/share/crubadan/ga/ANCIU
}

do_one()
{
echo "Indexing $1..."
rm -f $1.conf
cat ${HOME}/gaeilge/aimsigh/aimsigh/NNN.conf | sed "s/NNN/$1/" > $1.conf
swish-e -c $1.conf -f $1.tmp -S prog -v 1
mv -f $1.tmp $1.index
mv -f $1.tmp.prop $1.index.prop
}


preindex
cd /home/kps/seal/inneacs
do_one TEIDIL
do_one NNN
do_one YNN
do_one YYN
do_one NNY
do_one YNY
do_one YYY
