#!/bin/bash
if [ $# -ne 1 ]
then
	echo "Usage: seed URL"
	exit 1
fi
TEMPFILE=`mktemp`
wget -O "${TEMPFILE}" "${1}"
cat "${TEMPFILE}" | get_refs.pl "${1}" >> /usr/local/share/crubadan/ga/TOCRAWL
rm -f "${TEMPFILE}"
