#!/bin/bash
if [ $# -ne 1 ]
then
	echo "Usage: urlkill REGEXP"
	exit
fi
cd /usr/local/share/crubadan/ga
find sonrai -name '*.dat' | xargs egrep "^url.*$1" | sed 's/^sonrai\///' | sed 's/\..*//' |
while read x
do
	dockill "$x"
done
