#!/bin/bash
if [ $# -ne 2 ]
then
	echo "Usage: urlsub SEARCH REPLACE"
	echo "e.g. $ urlsub 'http://homepage.tinet.ie/' 'http://homepage.eircom.net/'"
	echo "Only use basic regexn (for sed)"
	exit 1
fi
cd /usr/local/share/crubadan/ga
find sonrai -name '*.dat' | xargs egrep -l "^url: .*${1}" |
while read x
do
	sed -i "/^url: /{s@${1}@${2}@}" $x
done
sed -i "s@${1}@${2}@" TOCRAWL
# now since we changed URLs in sonrai/, should make sure new ones
# are added to DEANTA so not re-downloaded
(cat DEANTA; find sonrai -name '*.dat' | xargs egrep '^url: ' | sed 's/^sonrai\/[0-9]*\.dat:url: //') | sort -u > DEANTA.tmp
mv -f DEANTA.tmp DEANTA
