#!/bin/bash

cd /usr/local/share/crubadan/ga
find ciu -name '*.txt' | xargs egrep -l 'Ã' |
while read x
do
	BADZ=`egrep -o 'Ã' $x | wc -l`
	OK=`egrep -o 'á' $x | wc -l`
	if [ $BADZ -gt $OK ]
	then
		echo "$x"
	fi
done |
while read y
do
	DATAFILE=`echo $y | sed 's/ciu/sonrai/' | sed 's/txt/dat/'`
	if egrep '^format: html' ${DATAFILE} > /dev/null
	then
		HTMLFILE=`echo $y | sed 's/ciu/taisce/' | sed 's/txt/html/'`
		echo "vilistextum -y UTF-8 --no-image --remove-empty-alt -errorlevel 0 $HTMLFILE - | recode -f \"u8..iso-8859-1\" > $y"
	else
		TEMPFILE=`echo $y | sed 's/^/~\/seal\//'`
		echo "cat $y | recode -f \"u8..iso-8859-1\" > $TEMPFILE"
	fi
done
